// <auto-generated />
namespace Antix.EASI.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addexaminations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addexaminations));
        
        string IMigrationMetadata.Id
        {
            get { return "201501271932567_add-examinations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
